<a href="https://colab.research.google.com/github/pedramjh99/Work-with-ANN-on-Churn_Modelling/blob/main/Work%20with%20ANN%20on%20Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Start work with neural network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report
from sklearn.neural_network import MLPRegressor, MLPClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataset.drop(["Exited","RowNumber","CustomerId","Surname"], axis=1)
y = dataset["Exited"]

In [4]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [5]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
le = LabelEncoder()
X['Gender'] = le.fit_transform(X['Gender'])

In [7]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

One Hot Encoding the "Geography" column

In [8]:
X = pd.get_dummies(X, columns=['Geography'], drop_first=False ).astype(int)

In [9]:
X

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2        0              1          1   
1             608       0   41       1    83807              1          0   
2             502       0   42       8   159660              3          1   
3             699       0   39       1        0              2          0   
4             850       0   43       2   125510              1          1   
...           ...     ...  ...     ...      ...            ...        ...   
9995          771       1   39       5        0              2          1   
9996          516       1   35      10    57369              1          1   
9997          709       0   36       7        0              1          0   
9998          772       1   42       3    75075              2          1   
9999          792       0   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0                  1           101348                 1                  0   
1                  1           112542                 0                  0   
2                  0           113931                 1                  0   
3                  0            93826                 1                  0   
4                  1            79084                 0                  0   
...              ...              ...               ...                ...   
9995               0            96270                 1                  0   
9996               1           101699                 1                  0   
9997               1            42085                 1                  0   
9998               0            92888                 0                  1   
9999               0            38190                 1                  0   

      Geography_Spain  
0                   0  
1                   1  
2                   0  
3                   0  
4                   1  
...               ...  
9995                0  
9996                0  
9997                0  
9998                0  
9999                0  

[10000 rows x 12 columns]

Feature Scaling

In [10]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [11]:
X

array([[-0.32622142, -1.09598752,  0.29351742, ...,  0.99720391,
        -0.57873591, -0.57380915],
       [-0.44003595, -1.09598752,  0.19816383, ..., -1.00280393,
        -0.57873591,  1.74273971],
       [-1.53679418, -1.09598752,  0.29351742, ...,  0.99720391,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -1.09598752, -0.27860412, ...,  0.99720391,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.91241915,  0.29351742, ..., -1.00280393,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.09598752, -1.04143285, ...,  0.99720391,
        -0.57873591, -0.57380915]])

### Splitting the dataset into the Training set and Test set

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Start for use Nneural network

### MLP Regression

In [13]:
mlp_reg = MLPRegressor(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=1000, random_state=42)
mlp_reg.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [14]:
y_pred_reg = mlp_reg.predict(X_test)

In [15]:
mse = mean_squared_error(y_test, y_pred_reg)
mae = mean_absolute_error(y_test, y_pred_reg)
r2 = r2_score(y_test, y_pred_reg)
rmse = np.sqrt(mse)

print(f'Mean Squared Error (MSE): {mse:.4f}')
print(f'Mean Absolute Error (MAE): {mae:.4f}')
print(f'R² Score: {r2:.4f}')
print(f'Root Mean Squared Error (RMSE): {rmse:.4f}')

Mean Squared Error (MSE): 0.1159
Mean Absolute Error (MAE): 0.2304
R² Score: 0.2823
Root Mean Squared Error (RMSE): 0.3404


### MLP Classification

In [16]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=1000, random_state=42)
mlp_clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [17]:
y_pred_clf = mlp_clf.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred_clf)
precision = precision_score(y_test, y_pred_clf, average='weighted')
recall = recall_score(y_test, y_pred_clf, average='weighted')
f1 = f1_score(y_test, y_pred_clf, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred_clf)

print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')
print('\nConfusion Matrix:')
print(conf_matrix)

Accuracy: 0.8310
Precision: 0.8283
Recall: 0.8310
F1 Score: 0.8296

Confusion Matrix:
[[1435  160]
 [ 178  227]]


In [19]:
print('\nClassification Report:')
print(classification_report(y_test, y_pred_clf))


Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1595
           1       0.59      0.56      0.57       405

    accuracy                           0.83      2000
   macro avg       0.74      0.73      0.73      2000
weighted avg       0.83      0.83      0.83      2000



### ANN With Tensorflow

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy', 'Precision', 'Recall', 'AUC'])

### Training the ANN on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 64, epochs = 100)

Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - AUC: 0.6104 - Precision: 0.2329 - Recall: 0.7347 - accuracy: 0.4458 - loss: 0.7448
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.5663 - Precision: 0.3524 - Recall: 0.2929 - accuracy: 0.7498 - loss: 0.6153
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.6033 - Precision: 0.4985 - Recall: 0.1096 - accuracy: 0.7930 - loss: 0.5398
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.6376 - Precision: 0.5877 - Recall: 0.0681 - accuracy: 0.8034 - loss: 0.4974
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.6946 - Precision: 0.6153 - Recall: 0.0622 - accuracy: 0.7981 - loss: 0.4729
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.7445 - Precision: 0.6381 - Recall: 0.1195 - accuracy: 0.8039 - loss: 0.4465
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7989 - Precision: 0.6893 - Recall: 0.2290 - accuracy: 0.8164 - loss: 0.4160
Epoch 8/100
125/125 ━━━━━━━━━━━━━━

In [26]:
y_pred = ann.predict(X_test)
y_pred_ann = np.round(y_pred)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


## Part 4 - Making the predictions and evaluating the model

In [27]:
accuracy = accuracy_score(y_test, y_pred_ann)
precision = precision_score(y_test, y_pred_ann, average='weighted')
recall = recall_score(y_test, y_pred_ann, average='weighted')
f1 = f1_score(y_test, y_pred_ann, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred_ann)

print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')
print('\nConfusion Matrix:')
print(conf_matrix)

Accuracy: 0.8570
Precision: 0.8471
Recall: 0.8570
F1 Score: 0.8483

Confusion Matrix:
[[1506   89]
 [ 197  208]]


### ANN With Pytorch

In [28]:
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x


In [29]:
X_train_np = X_train.values if isinstance(X_train, pd.DataFrame) else X_train
y_train_np = y_train.values if isinstance(y_train, pd.Series) else y_train

X_test_np = X_test.values if isinstance(X_test, pd.DataFrame) else X_test
y_test_np = y_test.values if isinstance(y_test, pd.Series) else y_test

X_train_tensor = torch.tensor(X_train_np, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_np, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test_np, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_np, dtype=torch.float32)

In [30]:
input_size = X_train.shape[1]
hidden_size = 64
output_size = 1

model = MLP(input_size, hidden_size, output_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [31]:
num_epochs = 100
batch_size = 32

for epoch in range(num_epochs):
    model.train()

    for i in range(0, X_train_tensor.size(0), batch_size):
        X_batch = X_train_tensor[i:i + batch_size]
        y_batch = y_train_tensor[i:i + batch_size]


        outputs = model(X_batch).squeeze()


        loss = criterion(outputs, y_batch)


        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/100], Loss: 0.2421
Epoch [20/100], Loss: 0.2385
Epoch [30/100], Loss: 0.2150
Epoch [40/100], Loss: 0.1949
Epoch [50/100], Loss: 0.1774
Epoch [60/100], Loss: 0.1650
Epoch [70/100], Loss: 0.1532
Epoch [80/100], Loss: 0.1411
Epoch [90/100], Loss: 0.1328
Epoch [100/100], Loss: 0.1283


In [32]:
model.eval()

with torch.no_grad():

    y_pred = model(X_test_tensor).squeeze()


y_pred_classes = (y_pred >= 0.5).int().numpy()
y_test_np = y_test_tensor.numpy()


accuracy = accuracy_score(y_test_np, y_pred_classes)
precision = precision_score(y_test_np, y_pred_classes)
recall = recall_score(y_test_np, y_pred_classes)
f1 = f1_score(y_test_np, y_pred_classes)
conf_matrix = confusion_matrix(y_test_np, y_pred_classes)

print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1-Score: {f1:.4f}')
print('Confusion Matrix:')
print(conf_matrix)


Accuracy: 0.8375
Precision: 0.6093
Recall: 0.5506
F1-Score: 0.5785
Confusion Matrix:
[[1452  143]
 [ 182  223]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [33]:
print(mlp_reg.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[False]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [34]:
print(mlp_clf.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[ True]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [35]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
[[False]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [36]:
print((model(torch.tensor(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]), dtype=torch.float32))).item() > 0.5)

False


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
